#cloud-config
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${ssh_public_key}
package_update: true     
packages: ${req_packages}

write_files:
  - path: /tmp/id_rsa
    permissions: '0600'
    encoding: b64
    content: ${base64encode(ssh_private_key)}

  - path: /tmp/hosts.ini
    permissions: '0644'
    encoding: b64
    content: ${base64encode(tpl_hosts)}

  - path: /tmp/extra.yml
    permissions: '0644'
    encoding: b64
    content: ${file_extra}

  - path: /tmp/kubespray.sh
    permissions: '0777'
    encoding: b64
    content: ${sh_kubespray}

  - path: /tmp/proxy
    permissions: '0644'
    encoding: b64
    content: ${base64encode(tpl_proxy)} 

  - path: /home/ubuntu/.Dockerfile
    permissions: '0644'
    encoding: b64
    content:  ${base64encode(docker_nginx)}    

  - path: /home/ubuntu/nginx-app.sh
    permissions: '0777'
    encoding: b64
    content:  ${base64encode(sh_app)}

  - path: /home/ubuntu/nginx-app.yml
    permissions: '0644'
    encoding: b64
    content: ${yml_app}  

  - path: /tmp/kube-prometheus.sh
    permissions: '0777'
    encoding: b64
    content: ${sh_prometheus}

  - path: /tmp/grafana-node-port.yml
    permissions: '0644'
    encoding: b64
    content: ${yml_grafana_node_port}

  - path: /home/ubuntu/authorized-key-diplom.json
    permissions: '0600'
    encoding: b64
    content: ${authorized_key_diplom}  

  - path: /home/ubuntu/credentials
    permissions: '0600'
    encoding: b64
    content: ${s3_key}      

  - path: /home/ubuntu/id_rsa.pub
    permissions: '0600'
    encoding: b64
    content: ${base64encode(ssh_public_key)}

  - path: /home/ubuntu/atlantis.sh
    permissions: '0777'
    encoding: b64
    content: ${sh_atlantis}    

  - path: /home/ubuntu/.terraformrc
    permissions: '0644'
    encoding: b64
    content: ${terraformrc}

runcmd:
  - sudo chown -R ubuntu:ubuntu /home/ubuntu
  - sudo -u ubuntu cp /etc/skel/.bashrc /etc/skel/.profile /home/ubuntu
  - sudo cp /tmp/id_rsa /home/ubuntu/.ssh/id_rsa; sudo chown ubuntu:ubuntu /home/ubuntu/.ssh/id_rsa
  - sudo cp /tmp/proxy /etc/nginx/sites-available/proxy
  - sudo ln -s /etc/nginx/sites-available/proxy /etc/nginx/sites-enabled/proxy  
  - sudo usermod -aG docker ubuntu
  - newgrp docker

  # helm
  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4 | bash
  - helm completion bash > ~/.helm_completion.sh
  - echo "source ~/.helm_completion.sh" >> ~/.bashrc
  - source ~/.bashrc

  - [ sudo, -u, ubuntu, -i, bash, -c, "/tmp/kubespray.sh ${name_control_node}" ]   
  - [ sudo, -u, ubuntu, -i, bash, -c, "/home/ubuntu/nginx-app.sh" ]    
  - [ sudo, -u, ubuntu, -i, bash, -c, "/tmp/kube-prometheus.sh" ]
  - [ sudo, -u, ubuntu, -i, bash, -c, "/home/ubuntu/atlantis.sh" ]