[kube_control_plane]
extra-vm-private0 ansible_host=192.168.2.25    ip=192.168.2.25  etcd_member_name=etcd1
private0 ansible_host=192.168.2.17    ip=192.168.2.17  etcd_member_name=etcd2
private1 ansible_host=192.168.3.15    ip=192.168.3.15  etcd_member_name=etcd3
private2 ansible_host=192.168.4.25    ip=192.168.4.25  etcd_member_name=etcd4
private5 ansible_host=192.168.6.29    ip=192.168.6.29  etcd_member_name=etcd5

[etcd:children]
kube_control_plane

[calico_rr]

[k8s_cluster:children]
kube_control_plane
calico_rr