[kube_control_plane]
extra-vm-private0 ansible_host=192.168.2.22    ip=192.168.2.22  etcd_member_name=etcd1
private0 ansible_host=192.168.2.34    ip=192.168.2.34  etcd_member_name=etcd2
private1 ansible_host=192.168.3.21    ip=192.168.3.21  etcd_member_name=etcd3
private2 ansible_host=192.168.4.18    ip=192.168.4.18  etcd_member_name=etcd4
private4 ansible_host=192.168.6.9    ip=192.168.6.9  etcd_member_name=etcd5

[etcd:children]
kube_control_plane

[calico_rr]

[k8s_cluster:children]
kube_control_plane
calico_rr